expediente_index:
    path:     /
    defaults: { _controller: "MesaEntradaBundle:Expediente:index" }
    methods:  GET

expediente_show:
    path:     /{id}/show
    defaults: { _controller: "MesaEntradaBundle:Expediente:show" }
    methods:  GET

expediente_new:
    path:     /new
    defaults: { _controller: "MesaEntradaBundle:Expediente:new" }
    methods:  [GET, POST]

expediente_edit:
    path:     /{id}/edit
    defaults: { _controller: "MesaEntradaBundle:Expediente:edit" }
    methods:  [GET, POST]

expediente_delete:
    path:     /{id}/delete
    defaults: { _controller: "MesaEntradaBundle:Expediente:delete" }
    methods:  DELETE

expediente_seguimiento:
    path:     /seguimiento
    defaults: { _controller: "MesaEntradaBundle:Expediente:seguimientoExpediente" }

expediente_timeline:
    path:     /{id}/timeline
    defaults: { _controller: "MesaEntradaBundle:Expediente:seguimientoExpedienteTimeline" }

expediente_imprimir_caratula:
    path:     /{id}/expediente_imprimir_caratula
    defaults: { _controller: "MesaEntradaBundle:Expediente:imprimirCaratula" }

expediente_imprimir_giro:
    path:     /{id}/{giroId}/expediente_imprimir_giro
    defaults: { _controller: "MesaEntradaBundle:Expediente:imprimirGiro" }

proyectos_index:
    path:     /proyectos
    defaults: { _controller: "MesaEntradaBundle:Expediente:proyectosIndex" }
    methods:  GET

proyecto_new:
    path:     /proyecto-new
    defaults: { _controller: "MesaEntradaBundle:Expediente:newProyecto" }
    methods:  [GET, POST]

proyecto_edit:
    path:     /{id}/proyecto-edit
    defaults: { _controller: "MesaEntradaBundle:Expediente:editProyecto" }
    methods:  [GET, POST]