form_dependencia:
    path: /form_dependencia
    defaults: { _controller: "AppBundle:Ajax:formDependencia" }

form_persona:
    path: /form_persona
    defaults: { _controller: "AppBundle:Ajax:formPersona" }

get_dependencias_por_nombre:
    path: /get_dependencias_por_nombre
    defaults: { _controller: "AppBundle:Ajax:getDependenciaPorNombre" }

get_cargos_por_nombre:
    path: /get_cargos_por_nombre
    defaults: { _controller: "AppBundle:Ajax:getCargosPorNombre" }

get_persona_por_dni:
    path: /get_persona_por_dni
    defaults: { _controller: "AppBundle:Ajax:getPersonaPorDni" }

get_tipos_proyectos:
    path: /get-tipos-proyectos
    defaults: { _controller: "AppBundle:Ajax:getTiposProyectos" }

get_mis_cargos_por_nombre:
    path: /get_mis_cargos_por_nombre
    defaults: { _controller: "AppBundle:Ajax:getCargosPorNombre" }
