version: '2'
services:
  app:
    container_name: ${DOCKER_IMAGE_NAME}_app
    hostname: ${DOCKER_IMAGE_NAME}_app
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - ${DOCKER_APP_PORT}:80
      - ${DOCKER_SOCKET_PORT}:3000
    volumes:
      - ${DOCKER_SRC}:/var/www/html
