imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UsuariosBundle/Resources/config/services.yml" }
    - { resource: "@MesaEntradaBundle/Resources/config/services.yml" }
    - { resource: easyadmin/ }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@UtilBundle/Resources/config/services.yml" }
    - { resource: "@ThemeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    app.path.expedientes_internos: /uploads/expedientes/internos
    app.path.expedientes_externos: /uploads/expedientes/externos
    app.path.dictamenes: /uploads/dictamenes/

framework:
    ide: "%ide%"
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        version: "%version%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
#        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
        - 'UtilBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

vich_uploader:
    db_driver: orm
    mappings:
        expedientes_internos:
            uri_prefix: "%app.path.expedientes_internos%"
            upload_destination: "%kernel.root_dir%/../web/uploads/expedientes/internos"
        expedientes_externos:
            uri_prefix: "%app.path.expedientes_externos%"
            upload_destination: "%kernel.root_dir%/../web/uploads/expedientes/externos"
        dictamen:
            uri_prefix: "%app.path.dictamenes%"
            upload_destination: "%kernel.root_dir%/../web/uploads/dictamenes"

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UsuariosBundle\Entity\Usuario
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"


#doctrine extentions
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            translatable: true
            timestampable: true
            blameable: true
            sluggable: true

ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
            toolbar: [ ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
                    ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat'], '/',
                    ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'], '/',
                    ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'],
                    ['Styles', 'Format']
                    ]

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: AppBundle:Menu:knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

tetranz_select2_entity:
    minimum_input_length: 2
    page_limit: 8
#    allow_clear: true
#    delay: 500
#    language: es
#    cache: false
#    cache_timeout: 0
#    scroll: true

knp_snappy:
    pdf:
        enabled:    true
        binary:     '%knp_snappy_binary%'

#KNPpaginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

