imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UsuariosBundle/Resources/config/services.yml" }
    - { resource: "@MesaEntradaBundle/Resources/config/services.yml" }
    - { resource: easyadmin/ }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@UtilBundle/Resources/config/services.yml" }
    - { resource: "@ThemeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    app.path.expedientes_internos: '%app_url%/uploads/expedientes/internos'
    app.path.expedientes_externos: '%app_url%/uploads/expedientes/externos'
    app.path.expedientes_anexos: '%app_url%/uploads/expedientes/anexos'
    app.path.dictamenes_anexos: '%app_url%/uploads/dictamenes/anexos'
    app.path.dictamenes: '%app_url%/uploads/dictamenes'
    app.path.sanciones: '%app_url%/uploads/sanciones'
    app.path.documentos: '%app_url%/uploads/documentos'
    app.path.varios: '%app_url%/uploads/varios'

framework:
    ide: "%ide%"
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        version: "%version%"
        kernelRootDir: "%kernel.root_dir%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
#        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
        - 'UtilBundle:Form:fields.html.twig'
        - ':Form:vich_widget.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'
    stream_options:
        ssl:
            verify_peer: false
            verify_peer_name: false
    spool: { type: memory }

vich_uploader:
    db_driver: orm
    mappings:
        expedientes_internos:
            uri_prefix: "%app.path.expedientes_internos%"
            upload_destination: "%kernel.root_dir%/../web/uploads/expedientes/internos"
        expedientes_externos:
            uri_prefix: "%app.path.expedientes_externos%"
            upload_destination: "%kernel.root_dir%/../web/uploads/expedientes/externos"
        dictamen:
            uri_prefix: "%app.path.dictamenes%"
            upload_destination: "%kernel.root_dir%/../web/uploads/dictamenes"
        sanciones:
            uri_prefix: "%app.path.sanciones%"
            upload_destination: "%kernel.root_dir%/../web/uploads/sanciones"
        documentos:
            uri_prefix: "%app.path.documentos%"
            upload_destination: "%kernel.root_dir%/../web/uploads/documentos"
        varios:
            uri_prefix: "%app.path.varios%"
            upload_destination: "%kernel.root_dir%/../web/uploads/varios"
        expedientes_anexos:
            uri_prefix: "%app.path.expedientes_anexos%"
            upload_destination: "%kernel.root_dir%/../web/uploads/expedientes/anexos"
            namer: "vich_uploader.namer_uniqid"
        dictamenes_anexos:
            uri_prefix: "%app.path.dictamenes_anexos%"
            upload_destination: "%kernel.root_dir%/../web/uploads/dictamenes/anexos"
            namer: "vich_uploader.namer_uniqid"

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UsuariosBundle\Entity\Usuario
    from_email:
        address:        '%mailer_user%'
        sender_name:    '%mailer_sender%'
    resetting:
        token_ttl: 86400
        email:
            from_email: # Use this node only if you don't want the global email address for the resetting email
                address:        '%mailer_sender_as%'
                sender_name:    '%mailer_sender%'
            template:   'UsuariosBundle:Resetting:email.txt.twig'
    service:
        mailer: fos_user.mailer.default


#doctrine extentions
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            translatable: true
            timestampable: true
            blameable: true
            sluggable: true

ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
            toolbar: [ ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
                    ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat'], '/',
                    ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'], '/',
                    ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'],
                    ['Styles', 'Format']
                    ]

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: AppBundle:Menu:knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

tetranz_select2_entity:
    minimum_input_length: 2
    page_limit: 8
#    allow_clear: true
#    delay: 500
#    language: es
#    cache: false
#    cache_timeout: 0
#    scroll: true

knp_snappy:
    pdf:
        enabled:    true
        binary:     '%knp_snappy_binary%'

#KNPpaginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

#bck

bm_backup_manager:
    database:
        production:
            type: postgresql
            host: '%database_host%'
            port: '%database_port%'
            user: '%database_user%'
            pass: '%database_password%'
            database: '%database_name%'

    storage:
        local:
            type: Local
            root: '%local_folder_backup%'
        dropbox:
            type: 'DropboxV2'
            token: '%dropbox_token%'
#            key: '%dropbox_key%'
#            secret: '%dropbox_secret%'
#            app: '%dropbox_app%'
            root: '%dropbox_root%'
        ftp:
            type: Ftp
            host: '%ftp_host%'
            username: '%ftp_username%'
            password: '%ftp_password%'
            root: '%ftp_root%'
            port: 21
            passive: true
            ssl: false
            timeout: 30
#

