theme:
    resource: "@ThemeBundle/Resources/config/routing.yml"
    prefix:   /theme

util:
    resource: "@UtilBundle/Resources/config/routing.yml"
    prefix:   /util

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

mesa_entrada:
    resource: "@MesaEntradaBundle/Resources/config/routing.yml"
    prefix:   /mesa-entrada

usuarios:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /usuarios

easy_admin_bundle:
    # this is just an example; update the value of 'resource' accordingly
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
#sesion
sesion:
    path: /sesion
    defaults: { _controller: "AppBundle:Sesion:index" }

sesion_login:
    path: /sesion/login
    defaults: { _controller: "AppBundle:Sesion:login" }

sesion_logout:
    path: /sesion/logout

app_display:
    path:     /pantalla
    defaults: { _controller: AppBundle:Default:display }

app_votar:
    path:     /sesion/votar
    defaults: { _controller: AppBundle:Mocion:votoConcejal }
    methods:  POST

get_ultima_sesion:
    path: /sesion/ultima-sesion
    defaults: { _controller: "AppBundle:Ajax:getUltimaSesion" }

get_buscar_expediente:
    path: /sesion/buscar-expediente
    defaults: { _controller: "AppBundle:Ajax:buscarExpediente" }

#sesion secretario
