dictamen_index:
    path:     /
    defaults: { _controller: "AppBundle:Dictamen:index" }
    methods:  GET

dictamen_crear:
    path:     /crear
    defaults: { _controller: "AppBundle:Dictamen:crear" }

dictamen_cargar:
    path:     /cargar
    defaults: { _controller: "AppBundle:Dictamen:index" }

dictamen_alta:
    path:     /alta
    defaults: { _controller: "AppBundle:Dictamen:altaDictamenAnterior" }

dictamen_editar:
    path:     /{id}/editar
    defaults: { _controller: "AppBundle:Dictamen:editarDictamenAnterior" }

dictamen_ver:
    path:     /{id}/ver
    defaults: { _controller: "AppBundle:Dictamen:verDictamen" }

dictamen_imprimir:
    path:     /{id}/imprimir
    defaults: { _controller: "AppBundle:Dictamen:imprimirDictamen" }

dictamen_asignar_a_expte:
    path:     /asignar-a-expte
    defaults: { _controller: "AppBundle:Dictamen:asignarAExpte" }


incorporar_dictamenes_en_sesion_index:
    path: /incorporar_dictamenes_en_sesion_index
    defaults: { _controller: "AppBundle:Dictamen:incorporarDictamenesEnSesion" }