dictamenod_index:
    path:     /
    defaults: { _controller: "AppBundle:DictamenOD:index" }
    methods:  GET

dictamenod_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:DictamenOD:show" }
    methods:  GET

dictamenod_new:
    path:     /new
    defaults: { _controller: "AppBundle:DictamenOD:new" }
    methods:  [GET, POST]

dictamenod_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:DictamenOD:edit" }
    methods:  [GET, POST]

dictamenod_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:DictamenOD:delete" }
    methods:  DELETE


dictamenod_incorporar_a_sesion:
    path:     /{dictamen}/incorporar-a-sesion
    defaults: { _controller: "AppBundle:DictamenOD:incorporarASesion" }
    methods:  [GET, POST]

dictamenod_incorporar_en_sesion:
    path:     /{dictamen}/incorporar-en-sesion
    defaults: { _controller: "AppBundle:DictamenOD:incorporarEnSesion" }
    methods:  [GET, POST]