sesion_index:
    path:     /
    defaults: { _controller: "AppBundle:Sesion:index" }
    methods:  GET

sesion_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Sesion:show" }
    methods:  GET

sesion_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sesion:new" }
    methods:  [GET, POST]

sesion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sesion:edit" }
    methods:  [GET, POST]

sesion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sesion:delete" }
    methods:  DELETE
