mesa_entrada_expediente:
    resource: "@MesaEntradaBundle/Resources/config/routing/expediente.yml"
    prefix:   /expediente

mesa_entrada_homepage:
    path:     /
    defaults: { _controller: MesaEntradaBundle:Default:index }

mesa_entrada_texto_definitivo:
    resource: "@MesaEntradaBundle/Resources/config/routing/textodefinitivo.yml"
    prefix:   /texto-definitivo