services:
#    util.example:
#        class: UtilBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    form.type.bootstrapcollection:
        class: UtilBundle\Form\Type\BootstrapCollectionType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: bootstrapcollection }

    tetranz_select2entity.select2entity_type:
            class: UtilBundle\Form\Type\Select2EntityType
            arguments:
                em: "@doctrine.orm.entity_manager"
                router: "@router"
                minimumInputLength: %tetranz_select2_entity.minimum_input_length%
                pageLimit: %tetranz_select2_entity.page_limit%
                dataType: %tetranz_select2_entity.data_type%
            tags:
                - { name: form.type, alias: tetranz_select2entity }