services:
#    util.example:
#        class: UtilBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    form.type.bootstrapcollection:
        class: UtilBundle\Form\Type\BootstrapCollectionType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: bootstrapcollection }

    form.type.jqueryautocomplete:
        class: UtilBundle\Form\Type\JqueryAutocompleteType
        tags:
            - { name: form.type, alias: jqueryautocomplete }

    tetranz_select2entity.select2entity_type:
            class: UtilBundle\Form\Type\Select2EntityType
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@router"
                - "%tetranz_select2_entity.minimum_input_length%"
                - "%tetranz_select2_entity.page_limit%"
                - "%tetranz_select2_entity.data_type%"
            tags:
                - { name: form.type, alias: tetranz_select2entity }


    UtilBundle\Services\NotificationsManager:
        public: false
        arguments:
            - "%redis_host%"
            - "%redis_port%"
            - "%redis_scheme%"

    notifications.manager:
        alias: UtilBundle\Services\NotificationsManager
        public: true