services:
#    votacion.example:
#        class: VotacionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    votacion.service:
        class: VotacionBundle\Services\VotacionService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@notifications.manager"