app_dependencia:
    resource: "@AppBundle/Resources/config/routing/dependencia.yml"
    prefix:   /dependencia

app_persona:
    resource: "@AppBundle/Resources/config/routing/persona.yml"
    prefix:   /persona

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_ajax:
    resource: "ajax/ajax.yml"
    prefix:   /ajax

app_parametro:
    resource: "@AppBundle/Resources/config/routing/parametro.yml"
    prefix:   /parametro

app_mocion:
    resource: "@AppBundle/Resources/config/routing/mocion.yml"
    prefix:   /mocion

app_tipomayoria:
    resource: "@AppBundle/Resources/config/routing/tipomayoria.yml"
    prefix:   /tipomayoria