app_proyectobae:
    resource: "@AppBundle/Resources/config/routing/proyectobae.yml"
    prefix:   /proyectobae

app_dictamenes:
    resource: "@AppBundle/Resources/config/routing/dictamen.yml"
    prefix:   /dictamen

app_dependencia:
    resource: "@AppBundle/Resources/config/routing/dependencia.yml"
    prefix:   /dependencia

app_persona:
    resource: "@AppBundle/Resources/config/routing/persona.yml"
    prefix:   /persona

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_ajax:
    resource: "ajax/ajax.yml"
    prefix:   /ajax

app_mocion:
    resource: "@AppBundle/Resources/config/routing/mocion.yml"
    prefix:   /sesion/mocion

app_tipomayoria:
    resource: "@AppBundle/Resources/config/routing/tipomayoria.yml"
    prefix:   /tipomayoria

app_concejal:
    path:     /concejal
    defaults: { _controller: AppBundle:Default:concejal }

documento_carta_organica:
    path:     /documento_carta_organica
    defaults: { _controller: AppBundle:Default:cartaOrganica }

sesiones:
    resource: "@AppBundle/Resources/config/routing/sesiones.yml"
    prefix: /interno-sesiones

#app_display:
#    path:     /display
#    defaults: { _controller: AppBundle:Default:display }

#app_votar:
#    path:     /votar
#    defaults: { _controller: AppBundle:Mocion:votoConcejal }
#    methods:  POST
