services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    manager.reportes:
        class: AppBundle\Services\ReportesManager
        arguments: ["@doctrine","@security.token_storage", "@router", "@assets.packages", "@knp_snappy.pdf"]

    AppBundle\Form\MocionType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]

    AppBundle\Form\SesionType:
            arguments: ['@doctrine.orm.entity_manager']
            tags: [form.type]


    AppBundle\Services\VotacionManager:
        public: false
        autowire: true

    votacion.manager:
        alias: AppBundle\Services\VotacionManager
        public: true
