easy_admin:
    entities:
        Cargo:
            class: AppBundle\Entity\Cargo
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'peso' }
                    - { property: 'muestraSoloCargo' }