easy_admin:
    entities:
        Comision:
            class: AppBundle\Entity\Comision
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'abreviacion' }
                    - { property: 'peso' }
