easy_admin:
    entities:
        Expediente:
            class: MesaEntradaBundle\Entity\Expediente
            form:
                fields:
                    - { property: 'tipoExpediente' }
                    - { property: 'texto', type: 'ckeditor'}
#                    - { property: 'letra' }
#                    - { property: 'fecha' }
                    - { property: 'iniciadores' , type: 'collection' , type_options: { by_reference: false, entry_type: MesaEntradaBundle\Form\AdminIniciadorExpedienteType } }
#                    - { property: 'expedienteExternoFile', type: 'vich_file' }