easy_admin:
    entities:
        Expediente:
            class: MesaEntradaBundle\Entity\Expediente
            form:
                fields:
                    - { property: 'tipoExpediente' }
                    - { property: 'texto', type: 'ckeditor'}
#                    - { property: 'letra' }
#                    - { property: 'fecha' }
#                    - { property: 'iniciador' }
#                    - { property: 'expedienteExternoFile', type: 'vich_file' }