easy_admin:
    entities:
        Parametro:
            class: AppBundle\Entity\Parametro
            list:
                fields:
                    - { property: 'slug' }
                    - { property: 'grupo' }
                    - { property: 'valor' }
                    - { property: 'orden' }
            form:
                fields:
                    - slug
                    - grupo
                    - valor
                    - orden
