easy_admin:
    entities:
        ProyectoBAE:
            class: AppBundle\Entity\ProyectoBAE
            list:
                fields: ['id', 'expediente', 'boletinAsuntoEntrado', 'creadoPor', 'fechaCreacion']
            form:
                fields:
                    - { property: 'expediente' }
                    - { property: 'boletinAsuntoEntrado' }
                    - { property: 'giros' , type: 'collection' , type_options: { by_reference: false, entry_type: MesaEntradaBundle\Form\GiroType } }
            search:
                fields: ['id', 'expediente.expediente']