easy_admin:
    entities:
        TipoExpediente:
            class: MesaEntradaBundle\Entity\TipoExpediente
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }